#!/usr/bin/python
# -*- coding: utf-8 -*-

import re
import sys
import os
from lxml import etree

def gettitles(html):
    xpath=[u'宁夏红盾信息宁夏红盾信息网', "//tr/td/span[@class='detail_titleblack']/text()",
           u'定西市质量技术监督信息网', "//p/font/span[@style='font-size: 14pt']/b/text()",
           u'温州市文成质量技术监督局',"//td/span[@class='title']/text()",
           u'洞头县质量技术监督局', "//tr/td[@style='font-size:20px; color:#005fb4; font-weight:bold; line-height:36px;']/text()",
           u'广东省汕尾市质量技术监督局', "//div/div[@class='news_title']/text()",
           u'广东省韶关市质量技术监督局', "//tr/td[@class='newstitle']/text()",
           u'宁波市北仑区质量技术监督局', "//div[@class='list show']/dl[1]/dt/text()",
           ur'金华市质量技术监督局[(金东分局)]?', "//tr/td[@class='title']/text()",
           ur'安吉县质量技术监督局\[http://www.ajzjj.gov.cn\]', "//tr/td[@style='font-size:14pt; font-weight:bold; color:#c80000; padding:20px 0 5px 0']/b/text()",
           u'湖州市质量技术监督局', "//tr/td/strong[@class='titlezt']/text()",
           u'河北省质量技术监督局', "//tr/td[@class='biaoti']/text()",
           u'安顺市工商行政管理局', "//tr/td[@style='font-weight:bold; font-size:14px; padding-top:8px;']/text()",
           u'本溪市工商行政管理局', "//div/span[@id='title']/text()",
           u'攀枝花质量技术监督局', "//tr/td[@id='title']/span[@class='bt']/text()",
           u'银川市质量技术监督局', "//div[@class='fl_content']/div[@class='article_title']/text()",
           u'松原市工商行政管理局', "//div[@class='xiangxi_title']/h1/text()",
           u'营口市质监局', "//tr/td[@class='lbnr_nrbt']/text()",
           u'乌鲁木齐质量技术监督局', "//tr/td/font/strong/text()" ,
           u'西双版纳州质量技术监督局',"//div/div[@id='bt']/text()",
           u'四川省质量技术监督局',  "//div/h1/text()",
           u'乌兰察布质量技术监督局', "//td/span[@class='STYLE87']/text()",
           u'呼和浩特市质量技术监督局', "//tr/td/span[@class='biaoti2']/text()",
           u'白城市工商行政管理局', "//td/div[@class='cs']/text()",
           u'内蒙古自治区工商行政管理局', "//tr/td[@class='font_xl_tit_14']/text()",
           ur'((呼和浩特市)|(包头市)|(乌兰察布市)|(锡林郭勒盟)|(鄂尔多斯)){1,1}工商行政管理局', "//td/font[@size='+2']/b/text()",
           u'江苏省常州质量技术监督局', "//div/div[@class='detail']/h1/text()",
           u'江苏省淮安质量技术监督局', "//tr/td[@align='center']/h3/text()",
           u'武汉市质量技术监督局', "//tr/td[@class='nei2bt']/h3/text()",
           u'河南省质量技术监督局', "//tr/td/div[@class='title7']/text()",
           ur'((新疆维吾尔自治区)|(阿勒泰地区)|(巴州)|(昌吉州)|(吐鲁番地区)|(哈密地区)|(塔城地区)|(石河子)|(伊犁州)){1,1}质量技术监督局',
           "//div/div[@id='info_title']/text()",
           u'温州工商局', "//tr/td[@class='article_title f_red']/text()|//tr/td[@class='article_title']/text()",
           u'广东省潮州市质量技术监督局', "//div/div[@class='topic_title']/text()",
           u'广东省茂名市质量技术监督局', "//tr/th[@class='a014']/text()",
           u'广东省质量技术监督局', "//div[@class='boxCon']/h1/text()|//div/p/b/span[@style='FONT-SIZE: 13.5pt']/text()",
           ur'((哈尔滨市)|(大庆市)|(佳木斯市)){1,1}质量技术监督局', "//tr/td[@style='font-size:14px;font-weight:bolder;']/text()",
           u'哈尔滨市工商行政管理局', "//tr/td[@class='wzbt']/text()",
           u'吉林市工商行政管理局', "//tr/td/font[@color='#FFFFFF']/text()",
           u'青海工商管理局', "//div/p/span[@class='c1087_title']/text()",
           u'四川工商动态', "//div[@class='nr_content']/h2/text()",
           u'济南市工商行政管理局', "//tr/td/span[@style='font-size: 17pt; font-weight: 700; LINE-HEIGHT: 40px;']/text()",
           u'广州市质量技术监督局', "//tr/td[@class='content-title']/div[@align='center']/text()",
           u'广州市工商行政管理局', "//tr/td[@class='content-title']/text()",
           u'西藏自治区工商行政管理局', "//tr/td[@class='rrr']/text()",
           u'锡林郭勒盟质量技术监督局', "//div/div[@class='news_content']/h1/text()",
           u'孝感市质量技术监督局', "//tr/td/span[@id='FormView1_Label7']/text()",
           u'信阳市工商行政管理局', "//tr/td/div[@align='center']/h4/text()",
           u'宁波市质量技术监督局江东分局', "//div/b/font/span/font[@class='H1']/text()",
           u'贺州市质量技术监督局', "//tr/td/div[@class='title_l']/text()",
           ur'<p>((焦作)|(开封)|(郑州)|(商丘)){1,1}市工商局',"//tr/td[@class='text_biaoti']//text()",
           u'河南省工商行政管理局', "//tr/td[@class='txt_bt']/text()",
           u'大庆市工商行政管理局', "//p[@class='MsoNormal1 STYLE6']//text()",
           u'定海质监分局', "//div/div[@class ='messagetitle']/text()",
           u'梅州市质量技术监督局', "//div/div[@class='newstitle']/text()",
           u'南宁市质量技术监督局', "//tr/td/h3[@style='margin:10px 0;']/text()",
           u'遵义市质量技术监督局', "//div/div[@id='d_title']/text()",
           ur'((周口)|(洛阳)|(济源)){1,1}市工商局', "//tr/td[@class='title']/h4/text()",
           u'广元质量技术监督局', "//tr/td/font/strong/text()",
           u'丹东市工商行政管理局', "//div[@class='rightMain']/div[@id='m_nr']/dl/dt//text()",
           u'东莞红盾信息网', "//tr/td[@class='font01']/text()",
           u'佛山工商局', "//tr/td[@class='bt_zi']/text()",
           u'海口市工商行政管理局', "//td/div[@class='px16-red']/span/text()",
           u'济宁质量监督局', "//div[@align='center']/strong/font/text()",
           u'嘉兴市质量技术监督局', "//tr/td[@class='titlex']/text()",
           u'长春质量诚信信息港', "//tr/td/span[@class='STYLE5']/text()",
           u'铜陵市质量技术监督局', "//tr/td/span[@id='Content_lblTitle']/text()",
           u'厦门市工商局红盾信息网', "//tr/td/div[@id='ivs_title']/text()",
           u'衢州市质量技术监督局', "//tr/td[@class='dbt']/text()",
           u'秦皇岛市质量技术监督局', "//div/strong/font[@style='font-size:22px']/text()",
           u'黔南州工商红盾信息网', "//table[@style='border-bottom:1px dotted #CCCCCC;']//td/text()",
           u'廊坊质量技术监督局', "//tr/td[@class='font_title']/text()",
           u'张家口市质量技术监督局', "//div/p[@style=' font-size:30px; COLOR: #00336c; padding-top:10px; padding-bottom:0px;']/text()",
           u'沧州市质量技术监督局', "//div/div[@class='title']/text()",
           u'沙洋县质量技术监督局', "//span[@class='title']/strong/font/text()",
           u'杭州市质量技术监督局江干分局', "//div/h2[@class='wto_news_title']/text() | //div[@class='news_main']/h2/text()",
           ur'北京市(.{0,4})质量技术监督局', "//div[@class='article-title']/text()",
           u'梧州市质量技术监督局', "//td/h3[@align='center']//text()",
           ur'(富阳市质量技术监督局)|(淳安质量网)|(临安质量网)', "//div/h2[@class='news_m_top_h']/text()",
           u'鞍山市工商局红盾网', "//tr/td[@style='border-bottom:1px solid #999999;']/text()",
           u'巴彦淖尔工商行政管理局', "//table[@class='lan16']//text()",
           u'包头市质量技术监督局', "//tr/td/div[@class='sj']/text()",
           u'湛江市质量技术监督局', "//div/h2[@class='news-title']/text()",
           u'阿勒泰地区工商局行政管理局网站', "//div/div[@class='style1']/text()",
           u'北京市工商行政管理局大兴分局', "//tr/td[@class='style4']/text()",
           u'北京市工商行政管理局石景山分局', "//div/div[@class='article-title']/text()",
           u'郴州红盾网', "//tr/td[@align='center']/h1/text()",
           u'赤峰工商行政管理局', "//tr/td[@align='center']/text()",
           ur'((滁州市)|(安徽省)){1,1}工商行政管理局', "//tr[1]/td[@align='center']/text()",
           u'德阳市工商局', "//div[@style='font-weight: bold; color: #1D124E; font-size: 16pt']/text()",
           u'东营红盾信息网', "//tr/td[@class='STYLE6']//text()",
           u'佛山12315', "//tr/td[@class='zwy_bt_zi']/text()",
           ur'武汉市((东湖新技术开发区)|(汉阳区)|(硚口区)|(青山区)){1,1}工商行政管理局', "//tr/td[@class='xilan_red']/text()",
           u'四平市工商行政管理局', "//tr/td/span[@id='Label1']/text()",
           u'广西防城港市质量技术监督局', "//div[@class='a']/h1/text()",
           u'公安县质监局', "//td[@id='tdTitle']/font/b/text()",
           u'贵阳市工商红盾信息网', "//div/div[@id='Content_Bt']/text()",
           u'((贵阳市)|(浙江兰溪市)|(镇江市)){1,1}质量技术监督局', "//tr[1]/td[@align='center']/text()",
           u'朝阳市质量技术监督局', "//tr/td/font[@size='4']/strong/text()",
           u'朝阳市工商行政管理局', "//div/span[@id='lTitle']/text()|//div/div[@id='n_title']/text()",
           u'海盐县质量技术监督局', "//tr/td/p[@class='14']/b/text()",
           u'汉川市工商行政管理局', "//div/p[@class='STYLE3']/text()",
           u'杭州国家高新技术产业（滨江）质量网', "//strong/span[@id='LabTitle']/text()",
           u'株洲市工商行政管理局', "//tr/td[@class='ShowArticleTitle']/text()",
           u'珠海市工商行政管理局', "//tr/td[@class='titW26']/text()",
           u'钟祥市工商局', "//td/font/font[@size='5']/text()",
           u'黄州区质量技术监督局', "//div[@class='infobox']/h2/text()",
           u'杭州市质量技术监督局西湖分局', "//div/h2[@id='h2_MainTitle']/text()",
           u'北海市质量技术监督局', "//tr[1]/td[@valign='center']/text()",
           u'浙江省德清县质量技术监督局', "//tr/td[@class='td_smalltitle']/text()",
           u'枣庄红盾信息网', "//div[@class='nr_list_top']/h2/text()",
           ur'((鹰潭)|(九江)){1,1}市质量技术监督局', "//td/span[@class='textht']/text()",
           u'益阳市工商行政管理局', "//td/p[@style=' font-weight: bold;  height:10px; color:#aa1a1a;font-size:22px;']/text()",
           u'烟台市质量技术监督局', "//tr/td[@class='leftzb']/text()",
           u'宣恩县工商行政管理局', "//tr/td[@class='font-16']/text()",
           u'宣城市工商行政管理局', "//tr/td/font[@size='4']/strong/text()",
           u'长春市工商行政管理局', "//div[@class='span10']/h3/text()",
           u'新余市质量技术监督局', "//tr/td/span[@class='textht']/text()",
           u'孝昌县工商行政管理局', "//td/p[@align='center']/strong/text()",
           u'杭州市质量技术监督局萧山分局', "//tr/td[@class='style22']/text()",
           u'象山县质量技术监督局', "//tr/td[@style='font-size:15px; font-weight:bold']/text()",
           u'成都市质量技术监督局', "//tr/td/div[@class='newsinfotitle']/text()",
           u'五峰土家族自治县质量技术监督局', "//td/span[@class='STYLE1']/text()",
           u'芜湖市工商行政管理局', "//div/h3[@id='NewsTitle']/text()",
           u'丽水市工商行政管理局', "//td[@style='text-align:center; font-size:18pt; font-weight:bold; color:#ea0505; line-height:40px;']//text()",
           ur'荆州市(.{1,5})质量技术监督局', "//tr/td[@class='message_title']/text()",
           u'荆门市质量技术监督局', "//td[@class='font-bai']/span/text()",
           u'晋城市工商行政管理局', "//tr/td[@class='title_1']/text()",
           u'天津市质量技术监督局', "//div/h2[@class='fs14']/text()",
           u'监利红盾信息网', "//tr/td/span[@class='STYLE13']/text()",
           u'惠州市质量技术监督局', "//div/p[@class='news_title']/span/text()",
           u'黄冈市黄州区工商行政管理局', "//tr/td[@align='center']/h2/text()",
           u'晋中工商红盾信息网', "//tr/td[@class='ArtName']/center/text()",
           u'淮北市工商行政管理局', "//td/p/b/font/text()",
           u'湖北省黄石市质量技术监督局', "//div/div[@class='third']/text()",
           u'河源市质量技术监督局', "//td/p/font/b/text()",
           u'河源市工商行政管理局', "//td[@style=' text-align: center; font-size: 15pt; color: Red']/div/text()",
           u'山东省滨州市工商行政管理局', "//tr/td[@class='t16_heise']/text()",
           u'德宏州质量技术监督局',"//div/span[@class='STYLE53']/text()",
           u'深圳市市场监督管理局',"//div[@class='center_center']/h1/text()",
           u'平湖市质量监督局',"//p/span[@class='font13']/text()",
           u'马鞍山市工商行政管理局',"//div[@class='wenzlb_wen']/h3/text()",
           u'老河口市工商行政管理',"//div/b/font[@size='4']/text()",
           u'衢江区质量技术监督局',"//tr/td[@class='fontMenu']/text()",
           u'内江市工商行政管理局',"//td/b/font[@class='ReadNewsTitle']/text()",
           u'丽水市质量技术监督局',"//tr/td/span[@class='ht']/text()",
           u'怀化市工商行政管理局',"//div[@id='content_head']/b[1]//text()",
           u'清远市质量技术监督局',"//div/div[@class='a_title']/text()",
           u'石河子工商行政管理局',"//tr/td[@class='mytitle']/span/text()",
           u'广西壮族自治区工商行政管理局',"//span[@class='culture_see']/font/b/text()",
           u'上城质量网',"//div[@id='view2']/span/text()",
           u'山西工商红盾网',"//div[@class='content_title']/text()",
           u'肇庆市工商行政管理局',"//div/div[@class='Title']/text()",
           u'泸州市质量技术监督局',"//div[@align='center']/b/font/text()",
           u'三亚市工商局',"//div[@class='article_cen']/h1/text()",
           u'石首市工商行政管理局',"//td/span[@class='style4']/font/text()",
           u'罗田县工商行政管理局',"//td/p[@class='bt']/text()",
           u'绵阳市质监局',"//td[@align='center']/font/b/text()",
           ur'((安阳)|(新乡)|((平顶山))){1,1}市工商局',"//td[@class='text_biaoti']/text()",
           u'桂林市质量技术监督局',"//td[@class='f-18 font-269']/text()",
           u'云南省工商行政管理局',"//td[@align='middle']/h2/text()",
           u'沈阳市质量技术监督局',"//tr[1]/td[@align='center']/b/text()",
           u'杨凌农业高新技术产业示范区',"//td[@valign='top']/table[1]/tr[1]/td[1]/text()",
           u'温州市质量技术监督局',"//div/span[@id='NewTitle']//text()",
           u'宁波市质量技术监督局江北分局',"//div[@class='list_body_right_bot']/h5/span[1]/text()",
           u'温州市文成质量技术监督局',"//td/span[@class='title']/text()",
           u'克拉玛依工商行政管理局',"//tr/td[@class='mytitle']/text()",
           u'甘肃省陇南市工商行政管理',"//div[@class='content']/h4/text()",
           u'湖北省来凤县工商行政管理局',"//div[@class='show_con_title']/h5/text()",
           u'四川省眉山质量技术监督局',"//td[@class='titlestyle40990']/text()",
           u'四川省南充质量技术监督局',"//div[@class='mainBox ']/ul[1]/li[1]/span/text()",
           u'青岛金质网',"//td/h3[@align='center']/font/text()",
           u'西双版纳州质量技术监督局',"//div/div[@id='bt']/text()",
           u'甘肃省质量技术监督局',"//div[@class='content']/h1/text()",
           ur'((五家渠)|(博州)){1,1}质量监督局',"//div/div[@id='info_title']/text()",
           u'宁夏质量技术监督局',"//td/font[@style='font-size:18px']/strong/text()",
           u'桐乡市质量技术监督局',"//tr/td[@class='s14']/b/text()",
           u'辽宁省工商行政管理局',"//div/span[@id='Labeltitle']/text()",
           u'西安工商行政管理局',"//tr/td[@class='titlestyle412189699_4546']/text()",
           u'五家渠工商行政管理局',"//td/span[@class='content_bt']/text()",
           u'巴州工商行政管理局',"//div/div[@id='info_toptitle']/text()",
           ur'((许昌)|(郑州))市工商行政管理局',"//td[@class='text_biaoti']/text()",
           u'武汉市江汉区工商行政管理局', "//td[@class='xilan_red']/text()",
           ]

    for s in range(0,len(xpath),2):
        if re.search(xpath[s],html.text):
            return xpath[s+1]
            break
    return ''
"""
    for s in xpath.keys():
        if re.search(s,html.text):
            print 'zheli ceshi: ',s
            return xpath[s]
            break
    return ''
"""
